/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bubblesort;

import javax.swing.JOptionPane;


/**
 *
 * @author hiperezr
 */
public class BubbleSortWithNumbers extends javax.swing.JFrame {

  private int dataQuantity;
  private int array[];
  /**
   * Creates new form BubbleSortWithNumbers
   */
  public BubbleSortWithNumbers() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    ClearButton = new javax.swing.JButton();
    AcceptButton = new javax.swing.JButton();
    dataQuantityInput = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    ClearButton.setText("Borrar");
    ClearButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ClearButtonActionPerformed(evt);
      }
    });

    AcceptButton.setText("Aceptar");
    AcceptButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AcceptButtonActionPerformed(evt);
      }
    });

    dataQuantityInput.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        dataQuantityInputActionPerformed(evt);
      }
    });

    jLabel1.setText("Inserte la cantidad de datos a ordenar");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(dataQuantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(AcceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(dataQuantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(28, 28, 28)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(AcceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
    dataQuantityInput.setText(""); // clear text
    dataQuantityInput.requestFocus();
  }//GEN-LAST:event_ClearButtonActionPerformed

  private void dataQuantityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataQuantityInputActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_dataQuantityInputActionPerformed

  private void AcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptButtonActionPerformed
    dataQuantity = Integer.parseInt(dataQuantityInput.getText()); // set the variable
    setArraySize(dataQuantity); // set the array size
    insertElementsInArray();
  }//GEN-LAST:event_AcceptButtonActionPerformed

  public void setArraySize(int size){ array = new int[size]; }
  
  public void insertElementsInArray(){
    int count = 1;
    for(int i=0; i< array.length; i++) {
      String currentElement = JOptionPane.showInputDialog(null, "Inserte un elemento en el arreglo", 
        "Elemento: " + count, JOptionPane.INFORMATION_MESSAGE);
      array[i] = Integer.parseInt(currentElement); // inserting the element
      count ++; // increase the variable
    }
    
    sortByBubbleMethod();
    showArray();
  }
  
  public void sortByBubbleMethod(){
    for(int i = 0; i < array.length - 1; i++){
      if (array[i] < array[i + 1]){
          int tmp = array[i+1]; // grab the next value
          array[i+1] = array[i]; // replace the current value in the next position
          array[i] = tmp; // replace the current position with the next value
      }
    } 
  }
  
  public void showArray(){
    StringBuilder arrayElements = new StringBuilder();
    for(int i = 0; i < array.length; i++){
      arrayElements.append(Integer.toString(array[i])).append(" ");
    }
    
    JOptionPane.showMessageDialog(null,
        arrayElements.toString(),
        "Elementos del array",
        JOptionPane.INFORMATION_MESSAGE);
  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(BubbleSortWithNumbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(BubbleSortWithNumbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(BubbleSortWithNumbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(BubbleSortWithNumbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new BubbleSortWithNumbers().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton AcceptButton;
  private javax.swing.JButton ClearButton;
  private javax.swing.JTextField dataQuantityInput;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
