package proyecto;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hiperezr
 */

import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Graphics;
import java.lang.Math;


public class FormWithShapes extends javax.swing.JFrame {

    /**
     * Creates new form FormWithShapes
     */
    public FormWithShapes() {
        initComponents();
        this.setBounds(0, 0, 600, 400);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        romboButton = new javax.swing.JButton();
        cuadradoButton = new javax.swing.JButton();
        circuloButton = new javax.swing.JButton();
        trianguloButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        romboButton.setText("Rombo");
        romboButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                romboButtonActionPerformed(evt);
            }
        });

        cuadradoButton.setText("Cuadrado");
        cuadradoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadradoButtonActionPerformed(evt);
            }
        });

        circuloButton.setText("Circulo");
        circuloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circuloButtonActionPerformed(evt);
            }
        });

        trianguloButton.setText("Triangulo");
        trianguloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trianguloButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Salir");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(trianguloButton)
                    .addComponent(circuloButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                .addComponent(romboButton)
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(cuadradoButton)
                    .addContainerGap(487, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(romboButton)
                .addGap(54, 54, 54)
                .addComponent(circuloButton)
                .addGap(106, 106, 106)
                .addComponent(trianguloButton)
                .addGap(28, 28, 28)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(cuadradoButton)
                    .addContainerGap(373, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private double calcularAreaCuadrado(float lado){
        double areaCuadrado = Math.pow(lado, 2);
        return areaCuadrado;
    }
    
    private void cuadradoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadradoButtonActionPerformed
        String ladoDelCuadrado = JOptionPane.showInputDialog(null, "Ingrese un lado del cuadrado", 
        "Area del cuadrado", JOptionPane.INFORMATION_MESSAGE);
        
        JOptionPane.showMessageDialog(null,
            calcularAreaCuadrado(Float.parseFloat(ladoDelCuadrado)),
            "El area del cuadrado es: ",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cuadradoButtonActionPerformed

    private double calcularAreaCirculo(float radio){
        double areaCirculo = Math.pow((3.1416 * radio), 2);
        return areaCirculo;
    }
    
    private void circuloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circuloButtonActionPerformed
        String radioDelCirculo = JOptionPane.showInputDialog(null, "Ingrese el radio del circulo", 
        "Area del circulo", JOptionPane.INFORMATION_MESSAGE);
        
        JOptionPane.showMessageDialog(null,
            calcularAreaCirculo(Float.parseFloat(radioDelCirculo)),
            "El area del circulo es: ",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_circuloButtonActionPerformed

    private double calcularAreaTriangulo(float base, float altura){
        double areaTriangulo = (base * altura) / 2;
        return areaTriangulo;
    }
    
    
    private void trianguloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trianguloButtonActionPerformed
        String base = JOptionPane.showInputDialog(null, "Ingrese la base del triangulo", 
        "Area del triangulo", JOptionPane.INFORMATION_MESSAGE);
        
        String altura = JOptionPane.showInputDialog(null, "Ingrese la altura del triangulo", 
        "Area del triangulo", JOptionPane.INFORMATION_MESSAGE);
        
        JOptionPane.showMessageDialog(null,
            calcularAreaTriangulo(Float.parseFloat(base), Float.parseFloat(altura)),
            "El area del triangulo es: ",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_trianguloButtonActionPerformed

    private double calcularAreaRombo(float diag1, float diag2){
        double areaRombo = (diag1 * diag2) / 2;
        return areaRombo;
    }
    
    private void romboButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_romboButtonActionPerformed
        String diagA = JOptionPane.showInputDialog(null, "Ingrese la diagonal 1 del rombo", 
        "Area del rombo", JOptionPane.INFORMATION_MESSAGE);
        
        String diagB = JOptionPane.showInputDialog(null, "Ingrese la diagonal 2 del rombo", 
        "Area del rombo", JOptionPane.INFORMATION_MESSAGE);
        
        JOptionPane.showMessageDialog(null,
            calcularAreaRombo(Float.parseFloat(diagA), Float.parseFloat(diagB)),
            "El area del rombo es: ",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_romboButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormWithShapes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormWithShapes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormWithShapes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormWithShapes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormWithShapes().setVisible(true);
            }
        });
    }

    private float area;
    
    public void paint(Graphics g){//metodo de la libreria graphics
        super.paint(g);//nombre del metodo paint, para crear las lineas o formas a dibujar en el frame
        
        
        g.setColor(Color.MAGENTA);
        
        //g.fillRect(100, 270, 50, 70);
        
        g.fillRect(20, 40, 50, 70);
        g.fillOval(20, 120, 50, 70);
        
        int[] vectorx2 = {50, 63, 38}; // 100% - 125% - 75%
        int[] vectory2 = {270, 320, 320};
        g.fillPolygon(vectorx2, vectory2, 3);
        
        
        g.setColor(Color.BLACK);
        int[] vectorx3 = {500, 550, 450};
        int[] vectory3 = {150, 200, 200};
        g.fillPolygon(vectorx3, vectory3, 3);
        int[] vectorx4 = {500, 550, 450};
        int[] vectory4 = {242, 200, 200};
        g.fillPolygon(vectorx4, vectory4, 3);        
    
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton circuloButton;
    private javax.swing.JButton cuadradoButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton romboButton;
    private javax.swing.JButton trianguloButton;
    // End of variables declaration//GEN-END:variables
}
