/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author hiperezr
 */
public class pelotaJPanel extends javax.swing.JPanel implements Runnable {

    int x = getWidth();
    Thread hilo;
    
    public pelotaJPanel() {
        initComponents();
        hilo = new Thread(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paint(Graphics g){
        g.setColor(getBackground());
        g.fillRect(0, 0, getWidth(), getHeight());
        g.setColor(Color.YELLOW);
        g.fillOval(x, getHeight()/2, 50, 50);
    }
    public void inicio(){ hilo.start(); }
    
    public void pausa(){ hilo.suspend(); }
    
    public void continuar(){ hilo.resume(); }
    
    @Override
    public void run(){
        try {
            while(true){
                while(x < getWidth()-30){
                    Thread.sleep(20);
                    x +=5;
                    repaint();
                }
                while(x > 0){
                    Thread.sleep(20);
                    x -=5;
                    repaint();
                }
            }
        } 
        catch(InterruptedException e) { System.out.println(e); }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
