/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import java.awt.Color;
import java.awt.Graphics;

public class Formas extends javax.swing.JFrame {

    public Formas() {
        initComponents();
        this.setBounds(0, 0, 600, 400);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

   
    public void paint(Graphics g){//metodo de la libreria graphics
        super.paint(g);//nombre del metodo paint, para crear las lineas o formas a dibujar en el frame
        
        //g.setColor(Color.GRAY);
        //g.drawLine(0, 70, 100, 70);
        g.setColor(Color.PINK);
        g.drawRect(150, 70, 50, 70); // dibujar rectangulo simple
        g.drawRoundRect(250, 70, 50, 70, 6, 6); // rectangulo con puntas ovaladas
        g.drawOval(350, 70, 50, 70); // ovalo
        
        int vectorX [] = {500, 550, 450};
        int vectory [] = {70, 120, 120};
        g.drawPolygon(vectorX, vectory, 3);
        
        g.setColor(Color.MAGENTA);
        g.fillRect(150, 270, 50, 70);
        g.fillRoundRect(250, 270, 50, 70, 6, 6);
        g.fillOval(350, 270, 50, 70);
        
        int[] vectorx2 = {500, 550, 450};
        int[] vectory2 = {270, 320, 320};
        g.fillPolygon(vectorx2, vectory2, 3);
        
        
        g.setColor(Color.BLACK);
        int[] vectorx3 = {500, 550, 450};
        int[] vectory3 = {150, 200, 200};
        g.fillPolygon(vectorx3, vectory3, 3);
        int[] vectorx4 = {500, 550, 450};
        int[] vectory4 = {242, 200, 200};
        g.fillPolygon(vectorx4, vectory4, 3);        
    
        
        
    }
}
